import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className="bg-white text-charcoal dark:bg-[#151515] dark:text-gray overflow-x-hidden"
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
