on:
  push:
    branches:
    - prod
    
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure web-sync AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.S3_SYNC_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.S3_SYNC_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Copy files to www.hello.coop website with the AWS CLI
      run: |
        aws s3 sync public/ s3://www-hello-coop

    # - name: Invalidate CloudFront cache for www.hello.coop
    #   run: |
    #     aws cloudfront create-invalidation --distribution-id E18QWJE5W61Q2O --paths "/*"
